CREATE SEQUENCE USER_ID 
START WITH 1 
INCREMENT BY 1;

CREATE TABLE USER_DETAIL
(USER_ID NUMBER PRIMARY KEY ,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
USER_NAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL,
CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
UNIQUE(USER_NAME));
DROP TABLE USER_DETAIL; 
DESC USER_DETAIL;
INSERT INTO USER_DETAIL(USER_ID,FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD)VALUES(USER_ID.NEXTVAL,'PRIYA','RAVI','PRIYARAVI','PRIYA24@');
SELECT * FROM USER_DETAIL;

CREATE SEQUENCE TIMESHEET_ID 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE TASK_ID 
START WITH 1 
INCREMENT BY 1;

CREATE TABLE TASK(
TASK_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TASK_NAME VARCHAR2(100)NOT NULL,
CREATED_BY VARCHAR2(100)NOT NULL,
ASSSIGNED_TO VARCHAR2(100)NOT NULL,
CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
ASSIGNED_DATE DATE DEFAULT SYSDATE NOT NULL
);
DESC TASK;
DROP TABLE TASK;

CREATE TABLE TIMESHEET(
TIMESHEET_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TASK_ID NUMBER NOT NULL,
FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID),
SPEND_TIME_HRS NUMBER NOT NULL,
COMMENTS VARCHAR2(200) NOT NULL,
ENTER_BY VARCHAR2(100) NOT NULL,
STATUS VARCHAR2(50) DEFAULT ('NOT APPROVED') NOT NULL,
APPROVED_BY VARCHAR2(100),
TIMESHEET_ENTERED_DATE DATE DEFAULT SYSDATE NOT NULL, 
CURRENT_DATE DATE DEFAULT SYSDATE NOT NULL,
STATUS_UPDATE_DATE  DATE DEFAULT SYSDATE NOT NULL
);
DROP TABLE TIMESHEET;
DESC TIMESHEET;

CREATE TABLE ROLE(
ROLE_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
ROLE VARCHAR2(100) NOT NULL
);
DROP TABLE ROLE;

CREATE SEQUENCE ROLE_ID 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE REPORT_ID 
START WITH 1 
INCREMENT BY 1;

CREATE TABLE REPORT(
REPORT_ID NUMBER NOT NULL,
REPORT_DATE DATE NOT NULL,
USER_ID NUMBER NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TASK_ID NUMBER NOT NULL,
FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID),
TIMESHEET_ID NUMBER NOT NULL,
FOREIGN KEY(TIMESHEET_ID) REFERENCES TIMESHEET(TIMESHEET_ID),
ROLE_ID NUMBER NOT NULL,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
);
DROP TABLE REPORT;
DESC USER_DETAIL;
DESC TASK;
DESC TIMESHEET;
DESC ROLE;
DESC REPORT;

COMMIT;
